nais/doc

content/redis.md

Ta gjerne en titt på om det er noen trykkfeil :)

Redis application config documentation

---

content/getting-started/vdi.md

Får `error: error upgrading connection: Upgrade request required` på utviklerimage om man ikke legger det til.

Legger til .nais.io i no_proxy

---

content/deploy/README.md
content/deploy/deployment-cli-templating.md

Retain as little information as possible but still be usable.

Shorten deploy documentation

---

content/redis.md

Merges inn etter at denne er rullet ut https://github.com/nais/naisd/pull/137

Doc for ny redis for naisd

---

basics/deploy.md

`with.resource` has also been updated to `with.resources` as per the newer version of the action.

Update GitHub Actions example to use action@0.4.0

---

SUMMARY.md
addons/kubernetes-dashboard.md
addons/leader-election.md
addons/naisjobs.md
addons/oauth-flow.md
addons/redis.md

I've mostly focused on fixing typos and wording, as well as some formatting. I've tried limiting the line length to 120 characters as well, although in some cases that wasn't possible.
Oh, and I've translated `naisjobs.md` to English. 🙂 I'm unsure about certain parts there (namely the parts describing `${vks_auth_path}` and `${vks_kv_path}`), but I figure it's good enough for now)

Addons rewrite

---

deployment/README.md

Hvis jeg har forstått det riktig.

Det er image og ikke container som pushes til Github Package Registry

---

deployment/README.md

Hvis jeg har forstått det riktig.

Forslag til endring av beskrivelse av 'how it works'

---

nais-application/manifest.md
observability/alerts/spec.md

Allowed values and spec on some fields in spec

---

basics/application.md

dead link to deploy to Kubernetes

---

nais-application/README.md

fixed a dead link

---

SUMMARY.md
addons/naisjobs.md

Step-by-step explanations for any adventurous beings attempting to use native Jobs/CronJobs on-prem.
Live preview here - https://doc.nais.io/v/naisjobs/addons/naisjobs

flesh out naisjobs with more examples and explanations

---

device/install.md

Updated the doc
- Added a bulletpoint for kubeconfig
- Moved Kollide below the installation list

Updated the doc on kubeconfig

---

README.md

Reverts nais/doc#93, ref. superscript not functioning as intended (source: https://stackoverflow.com/a/15156585/1503549).

Revert "Add explanatory links to the term "Turnkey solutions""

---

README.md

Also, since line with 4 sentences has been "dirtied" by this commit's
principal change (ref: git blame), spread sentences to one per line.

Add reference explaining "ROS" term at first occurrence

---

README.md
book.json

Now with hopefully functioning superscript!
Inspired by: https://github.com/GitbookIO/plugin-superscript/

Add explanatory links to the term "Turnkey solutions

---

clusters/README.md

Ref https://github.com/nais/doc/issues/99.

Clarify clusters section name

---

SUMMARY.md
addons/idporten.md
addons/tokenx.md
nais-application/reference.md

Base my description on the phenomenal documentation made by @tronghn  for Azure-AD Applications.

Digdirator doc

---

addons/kafka.md

These are the various approaches for migrating to Aiven I could think of.

Guides for migrating to Aiven

---

addons/kafka.md

Oppdatert forslag til metadata

default verdier for datakatalogen metadata for kafka topics

---

docs/addons/kafka.md
docs/addons/naisjobs.md
docs/basics/access.md
docs/security/auth/tokenx.md
mkdocs.yml

Nice, thanks! Merged!
Co-authored-by: @chinatsu

small fixes (#132), layout changes

---

docs/legal/nais-pvk.md
docs/legal/roles-responsibilities.md
mkdocs.yml

and a small fix in roles/responsibilities

reorganizes documents

---

docs/nais-application/nais.yaml/reference.md

Co-authored-by: @Kyrremann 
Co-authored-by: @chinatsu

refactor: Sort references for NAIS application alphabetically

---

docs/basics/teams.md

Azure portal is now off limits. Edited/Added links to self-service "My Groups" to "teams doc"

updated groups management links

---

docs/nais-application/nais.yaml/reference.md
docs/persistence/postgres.md

Forslag til endring av dokumentasjon for å få frem manuelle steg som av og til må gjøres ifm postgres secrets hvis man endrer postgres oppsettet, og for å rette en feil.

Forslag til endring av dokumentasjon 

---

docs/device/install.md

Updated instructions from vegar.sechmann.molvig@nav.no

Update instructions for ubuntu installation

---

docs/device/unenroll.md
docs/device/update.md
mkdocs.yml

i'm thinking some specific pages about these operations could be useful

add unenroll and update naisdevice docs

---

README.md

There was a minor typo in URL to doc.nais.io

Corrected URL to doc.nais.io

---

docs/security/auth/tokenx.md

Witch claims Tokendings always provieds and claims that is passed on. should maby be more defined, updated token
from idporten.

Issue with not knowing with claims is in token

---

docs/addons/naisjobs.md
docs/basics/application.md
docs/deployment/README.md
docs/deployment/allowed-registries.md
docs/nais-application/nais.yaml/reference.md

In the spirit of trying to keep up with the (Github Docker) future.

Document possible usage of Github Container Registries in nais/navikt Github orgs.

---

docs/device/troubleshooting.md
docs/device/uninstall.md
mkdocs.yml

Added information about howto remove Kolide from system

Added uninstall.md to device

---

docs/deployment/README.md

Legge til doc for NAIS_CLIENT_ID, måte gå i naiserator koden for å finne den

Legge til doc for NAIS_CLIENT_ID

---

docs/addons/unleash.md

For feature toggles specifically.
Change inspired by: https://nav-it.slack.com/archives/C9BPTSULS/p1616667343002100?thread_ts=1616666135.002000&cid=C9BPTSULS

Unleash: Minor improvements + add recommended best practices

---

docs/nais-application/nais.yaml/reference.md
mkdocs.yml

1. Grouped similar specs into (by default) collapsed blocks.
2. Sorted some that were not listed in alphabetical order into alphabetical order.
3. Added vertical separators between each item/group.
4. Standardized "Example/Default/Allowed Values/Required" tags.

Refurbish /nais-application/nais.yaml/reference page

---

docs/security/auth/tokenx.md

Oppdaterer dokumentasjon om TokenX etter samtale med Tommy og Youssef.

TokenX: Loginservice er støttet. Claims for ikke-standard informasjon.

---

docs/observability/logs/README.md

Refer to https://github.com/navikt/naudit for specifics, since audit logging is not relevant for all applications.
Fixes https://github.com/nais/doc/issues/182

Add section about audit logging

---

docs/device/install.md
docs/device/uninstall.md
docs/device/update.md

merge when we have confirmed that https://github.com/nais/device/pull/189 works

use package managers on mac and linux

---

docs/README.md

Co-authored-by: @frodesundby <frode.sundby@nav.no>

Add some words about the NAM initiative

---

docs/persistence/influxdb.md

Hi Kyrre, made a couple of suggestions. Perhaps consider leaving an example command or link for testing from naisdevice. (see placeholder ~line40)

suggestions re. aiven influxdb

---

docs/observability/logs/README.md

Jeg oppdaterte log-seksjonen med litt informasjon om hvordan man går frem for å få tilgang. Kom gjerne med forbedringsforslag hvis det er noen ukjente regler/conventions som må tas høyde for i dokumentasjonen her.

Update logs section with access description

---

docs/naisjob/README.md

fixed wrong schedule format/syntaxt : https://www.shellhacks.com/crontab-format-cron-job-examples-linux/

Fix schedule format

---

docs/appendix/json-schema.md
mkdocs.yml

Requires https://github.com/nais/liberator/pull/33
Currently, only VSCode is tested and documented. Would be nice to have at least intellij before merging, if someone is willing to help :)

Add initial documentation for how to use json schema for validation

---

docs/naisjob/README.md

just running it by here if someone wants to have a look. otherwise i'll merge it in a few hours

document ginuudan

---

docs/persistence/postgres.md

Add missing hyphen on condition parameter

---

docs/observability/alerts/README.md

Er ment å forbedre issueen https://github.com/nais/doc/issues/223

Vær eksplisitt på at hvilke labels som er tilgjengelige for alerts notifications avhenger av spørringen

---

docs/addons/leader-election.md

Får regelmessig mer en en leader

---

docs/naisjob/reference.md
docs/persistence/postgres.md

* Added postgres default tier
* Added available tiers
* Links to GCP SLA and instance documentation
Some discussion in `#nais-familie` https://nav-it.slack.com/archives/GREQVPXHS/p1639144976082500?thread_ts=1638365764.078500&cid=GREQVPXHS

Postgres sizing, defaults, available tiers and documentation

---

docs/addons/leader-election.md

Dette bør ikke merges før vi er klare til å sende ut announcement. Utkast til announcement kommer på Slack litt senere.

Update leader election documentation

---

docs/appendix/json-schema.md

Tok meg litt tid før jeg forsto hvorfor valideringen ikke funket, så jeg legger ved denne for at ikke flere trenger å gjøre samme feil.

Oppdaterer skjema for validering av YAML i VSCode

---

docs/addons/leader-election.md

* Info about return string of ELECTOR_PATH without protocol

Improve leader-election doc with link to container image and spec api

---

docs/observability/logs/README.md

Fixes https://github.com/nais/doc/issues/249
kyrre edit: endret fra Løser til Fixes for at Github automatisk skal lukke issuet. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Secure log: Hva menes med "team" + refaktorering

---

docs/cli/install.md
docs/device/install.md

Make use of pre-existing folders, thus simplifying nais deb PPA install.

refactor: Simplify nais deb PPA install

---

docs/persistence/postgres.md

Fix psql install guide link

---

.github/dependabot.yml
CODEOWNERS

This sets up @dependabot to update dependencies in this repository.

Add GitHub @dependabot configuration

---

docs/persistence/postgres.md

Database instance takes a few minutes to be created the first time

Added in note for creating database instance

---

docs/deployment/README.md

Updates the versions for actions used in the NAIS workflow example.

Update GitHub Actions workflow example

---

docs/nais-application/ingress.md

* Custom max body size
* Custom proxy buffer size
* Custom timeouts
* WebSockets Support

Add more documentation for ingress nginx configurations

---

docs/nais-application/ingress.md

Add links to Kibana logs for nginx ingress controller and some helpull debugging tips when things are not going as planned.

Add links to nginx controller logs and debugging

---

docs/observability/logs/README.md

Legger til litt mer utfyllende informasjon som IT trenger for å mer sømløst opprette en AD-gruppe for secure logs.

Update Create an AD-group with template for IT

---

docs/nais-application/access-policy.md

Remove statement about _inbound_ rules and clarify what it applies to

Clarify outbound rules

---

docs/naisjob/reference.md

Note UTC tz for naisjobs

---

docs/observability/metrics.md

Use Prometheus Pushgateway over deprecated Sensu.

Document Prometheus Pushgateway

---

docs/persistence/kafka/manage_topics.md

See https://github.com/nais/features/issues/7

kafka/topic: add separate section for config; describe max message size and segment rolling

---

docs/security/antivirus.md

Update ClamAV address in `fss` and generally update the documentation.

Update ClamAV documentation

---

docs/naisjob/README.md

Jeg tror at "How do I..." er mer lettlest enn "How to I...", men engelsk er ikke morsmålet mitt heller...

fix(language): title

---

docs/persistence/kafka/avro_and_rest.md

Adds sections on creating and fetching avro schemas

Adds sections on creating and fetching avro schemas

---

docs/deployment/troubleshooting.md

Is the table correct and complete?

Add section about checking related resources when troubleshooting secrets

---

docs/device/update.md

removed link to homebrew and added the terminal commands required.

Direct description of Mac update

---

docs/observability/alerts.md

to make it clearer that it is about Custom AlertmanagerConfig

Update onprem alert

---

docs/material_theme_stylesheet_overrides/uu.css

Bump link contrast to 4.6 from 4.15

---

docs/guides/README.md
docs/guides/basics.md
mkdocs.yml

Add NAIS Guides section

---

docs/guides/basics.md

Add alternatives to using docker in NAV

Add docker tool alternatives

---

docs/basics/teams.md

A user at the nais onboarding got confused on whether to rotate the key before copying

Make rotate keys more separate from Access key

---

docs/cli/install.md
docs/cli/troubleshooting.md
mkdocs.yml

Added Windows troubleshooting for nais-cli.
Not included for naisdevice, as I've not encountered the problem here and cannot provide a correct description of how the error would appear for the user.

nais-cli-troubleshooting

---

docs/security/README.md
mkdocs.yml

Add Security Overview for NAIS
- Threat models
- References to sikker.nav.no
- References to TryggNok

Add Security Overview

---

docs/basics/teams.md

- rewrite introduction and overview
- add information about deleting a team

Update nais teams docs

---

docs/persistence/postgres.md

`nais postgres` has been used a while without any major issues. Given that it should be easier than using `gcloud` and `cloud-sql-proxy` directly, update the docs to use `nais postgres`

postgresql: Change personal database access recommendations

---

docs/observability/tracing.md

Jeg visste ikke hva ordet "tracing" betydde. Det gjorde at det ble bom stopp da jeg skulle lese gjennom Nais-dokumentasjonen. Så for andre i samme situasjon la jeg til en lenke til en kort og forhåpentligvis god definisjon/forklaring.
Dette er vel det samme som mange kjenner som "call-ID" og "correlationID"? Hadde det vært en ide å si det? Blir kansje for mye tekst...

Lenke til en forklaring av hva tracing er

---

docs/persistence/README.md

I also let IntelliJ format the table, since the first column needed to be wider.

fix-a-link

---

docs/how-to-guides/command-line-access/.pages
docs/how-to-guides/command-line-access/setup.md
docs/how-to-guides/command-line-access/troubleshooting.md
docs/how-to-guides/nais-cli/troubleshooting.md

Mac-troubleshooting; 
* commandline-access
* nais-cli

Troubleshoot nais access

---

docs/how-to-guides/persistence/postgres.md

Link directly to usage of insights

fix(postgres): Link to query insights returns 404

---

docs/tutorials/hello-nais.md

Kopierte yaml fra introen, og skjønte ikke hvorfor appen ble slettet av seg selv...
Så la til en setning om det "for future reference".

Add warning about ttl in intro

---

docs/tutorials/hello-nais.md

Litt rask å commite - fikser 404 :)

---

docs/build/how-to/build-and-deploy.md

After Gargle nais/system#69 we keep images that are in use as well

Gar: Inform we're keeping images in use

---

docs/build/how-to/dependabot-auto-merge.md

See https://www.synacktiv.com/en/publications/github-actions-exploitation-dependabot for details

Suggest safer automerging

---

docs/operate/naisdevice/how-to/update.md

github.com/naid is another existing account.

Fix typo in naisdevice/how-to/update

---

.github/dependabot.yml

Update dependabot schedule to run weekly on Mondays at 09:00.

Run dependabot updates weekly at monday 09:00

---

docs/build/how-to/use-image-outside-nais.md

See https://github.com/nais/system/pull/201#issuecomment-2758252291

Clarification ref nais/systems' initiative

---

docs/operate/cli/how-to/install.md
docs/operate/naisdevice/how-to/update.md

use apt instead apt-get, include ppa tip for nais-cli

---

docs/workloads/reference/environments.md

Forsøker meg på å oppdatere dokumentasjonen for vårt nye miljø.

La til prod-environment for tenant atil

---

docs/operate/naisdevice/how-to/install.md

Flytter steget for install av curl før steget for PPA repo updatering, da kommandoen benytter curl.

Update ubuntu install steps in naisdevice section
