observability/alerts/recommended_alerts.md

Dette er sikkert en lite viktig smak-og-behag-ting, men jeg liker å si hvilken verdi som printes før jeg printer den. Det vil forbedre disse ikke-så-pene alert-meldingene jeg har fått i Slack:
```
[FIRING:1]
finn-kandidat-api er nede in dev-fss
er nede i 
action: kubectl describe pod  -n  for events, og kubectl logs  -n  for logger
```
```
[FIRING:1]
høy feilrate i logger in dev-fss
@here | 
action: Sjekk loggene til rekrutteringsbistand-api i default, for å se hvorfor det er så mye feil
```

Pynt på tekst, eksplisitt på hvilken verdi man prøver å vise

---

observability/alerts/example_alerts.md

Fra feilmelding fra kubectl ved forsøk på opprette alerts:
spec.alerts.severity in body should match 'good|warning|danger|#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})'

Ugyldig verdi i eksempel

---

observability/alerts/recommended_alerts.md

* Er ikke Java- eller Jetty-spesifikk
* Skiller mellom klientfeil og serverfeil for å kunne gi ulikt toleransenivå for dem.

Forbedre alert for høy andel HTTP feilresponser

---

addons/azure-ad.md
basics/application.md
deployment/README.md
nais-application/manifest.md
nais-application/max-example.md
nais-application/min-example.md

it is to my understanding that team namespaces are generally recommended practice for those who have the chance to migrate
as such, the examples around the documentation should reflect that as a best practice for those who might reference them for their own configurations
i may have been a bit overzealous with changing the examples, so have a quick look to see if i haven't changed an alert (which afaik should stay in `default`) or something

Update examples with team namespaces

---

clusters/team-namespaces.md

Mostly formatting for readability. Some more elaboration on service discovery in general (which could perhaps be moved to it's own page).
Live preview: https://doc.nais.io/v/team-namespaces-cleanups/clusters/team-namespaces

clean up and restructure team namespaces

---

device/install.md

Argumentation:
1. Newbies (like myself) could use a helping hand finding referenced resources (like the `kubeconfigs` repo).
1. Same goes for non-newbies who may have forgotten.
2. `kubeconfigs` is a private repo - thus access concerns should be mediated by the authentication/authorization layers provided by log-in/read-permissions.

kubeconfigs/naisdevice: Link Repo URL & make instructions explicit

---

clusters/migrating-to-gcp.md

There's no longer any reference in the GCP document for how the
application deployment mechanism for on-premise clusers works.

Update section referencing non-existent documentation/differences.

---

persistence/redis.md

The default `redis` baseimage doesn't support setting password without supplying a `.conf` file with some expected key/value format. If you've created a secret containing `REDIS_PASSWORD` for configuring the redis metrics exporter image, then you'll have to duplicate the password value to another secret for configuring the `redis` instance itself.
We'd have to either use vanilla k8s to set the password through the command line arguments, or use a custom image that supports supplying the password. The latter involves the least amount of work, so the examples are updated to recommend using this.
Live preview here: https://doc.nais.io/v/redis-cleanup/persistence/redis

redis: update examples and fix secure redis configuration

---

addons/kafka.md

Legger til informasjon om keystores og truststores, implementert i nais/kafkarator#3.
`KAFKA_KEYSTORE_PATH` og `KAFKA_TRUSTSTORE_PATH` vil bli definert i naiserator på samme måte som de andre `*_PATH` variablene (PR kommer til uka).

Add information about keystore env-variables

---

legal/app-ros.md

When I was reading this I was looking for info on what is ROS and an aswer to when do a product team need to do a ROS assessment. The old link did not answer that, this one does, or rateher the page links to other pages that does, including the page the old link pointed to. Is this an improvenment, perhaps?

Is this a better link to ROS documentation?

---

.dockerignore
.gitignore
Dockerfile
README.md
docker-compose.yaml

TODOS:
1. [x] Ensure `mkdocs serve` inside docker container can map to `0.0.0.0`.
Ref: https://github.com/mkdocs/mkdocs/issues/2108
2. [x] Configure docker-compose to allow hot-reloading to work (mounting
instead of COPY inside of `Dockerfile`).
3. [x] Write up proper how-to/documentation.

feature: Add local pre-view environment with Docker

---

docs/custom/javascript/analytics.js
docs/custom/overrides/main.html
mkdocs.yml

addresses #140 
this adds a few customizations in the form of javascript and a template extension. the changes run data through the inhouse proxy about what pages the reader looks at, e.g. `/` for the main page, `/basics/access` for access from laptop, and so on. this data point was the easiest and most sensible thing i could add in which gives us the ability to see which pages are the most popular ones.
the large code block in `docs/custom/overrides/main.html` uses the snippet described in the [amplitude sdk documentation](https://developers.amplitude.com/docs/javascript), with some inspiration taken from [navikt/tp-malekode](https://github.com/navikt/tp-malekode/blob/main/amplitude.md). the general method for extending the stack is described in the [material for mkdocs …

adds amplitude integration

---

docs/nais-application/nais.yaml/reference.md

It is also used for AZURE_APP_PRE_AUTHORIZED_APPS in FSS apps

Access policy is not GCP only

---

docs/persistence/postgres.md

Add information about the restriction on connecting to database instances.
Someone implementing a new service or migrating an existing one should be aware of this restriction.

Only one app per postgresql instance

---

docs/device/install.md

- Renamed Ubuntu title for easier hyperlinking and title conventions
- Added information after installing Kolide to go back to the main install guide to continue installing naisdevice app
- Added information when connecting to naisdevice, by pointing readers to the main install guide if the reader can't find their naisdevice icon

naisdevice app install instructions

---

docs/persistence/bigquery.md
mkdocs.yml

Also, move all GCP persistent storage into its own sub-heading in
navigation tree.
Co-authored-by: @cteig <christine.teig@nav.no>

Docs: Add bigquery documentation

---

docs/observability/alerts/recommended_alerts.md

- Previously it alerted on at least one replica being available, which is the opposite of what one wants

Alert of no replicas available

---

docs/cli/commands/aiven.md

Updated from `read` to `write` in the example topic.yml in nais-cli aiven commands. `write` dit not work when tested. `read` did, which makes sense, since the permission applies to a topic consumer, and the consumer sets the topic offset.

nais-cli aiven commands ACL description fix

---

docs/basics/access.md

Starship fungerer knirkefritt for meg i Ubuntu med bash. Starship skal i følge reklamen fungere for flere OS og flere shell. Lisens er open source og prosjektet er aktivt.

Legg til Starship som anbefalt verktøy for å se aktiv  k8s context og namespace i terminalen

---

docs/diagrams/out/persistence/bigquery-metabase.svg
docs/diagrams/src/persistence/bigquery-metabase.puml
docs/persistence/influxdb.md
mkdocs.yml
poetry.lock
pyproject.toml

Also added mkdocs plugin that generates PlantUML diagrams. Any diagram under `docs/diagrams/src` will be generated on serve.
Probably best practice to run serve locally while editing, and commiting the generated file along with the puml-file changes, but it will always try to generate a new file if source is changed.

Added section about recommended alternative to InfluxDB on Aiven

---

docs/persistence/kafka/offsets.md

This link fails: https://help.aiven.io/en/articles/2661525-viewing-and-resetting-consumer-group-offsets
I believe this is the correct one
https://developer.aiven.io/docs/products/kafka/howto/viewing-resetting-offset

Unreachable link to Aiven article

---

docs/naisjob/README.md

There is no `name` argument, kubectl gives an error message when using the suggested syntax: `Error: unknown flag: --name`

These is no name argument; updating adhoc job syntax

---

docs/observability/alerts/recommended_alerts.md

Er ikke helt sikker på om de er helt like, men byttet metrikken fra `traefik_backend_requests_total` til `response_total` som blir laget av Linkerd proxien.  Denne har tilgang til ekstra labels, så kunne utnytte namespace og appname. 
La også inn et par linjer for å gjøre det lettere å finne `<replaceme>`s

Add an updated recommendation that for GCP as well.

---

docs/naisjob/reference.md

`ttlSecondsAfterFinished` was previously enabled through the ttl-controller alpha, which was only enabled on-premise. Since k8s 1.21, it has been moved to beta and is enabled by default, which makes it available for general use in our gcp clusters.

ttlSecondsAfterFinished is now available in gcp

---

docs/persistence/kafka/application.md

Dropped ruby, as they don't have an example for it any longer.

Fixed broken URLs for kafka-codesamples

---

docs/security/auth/maskinporten/README.md

I've effectively made the abstract the _document_, most links to the Maskinporten docs have been removed or changed to internal doc links so that people may easier find out what they need to do

restructure abstract to point to our internal docs

---

docs/device/services.md

Previously the Postgres howto was a link to Slack, which eventually will expire. Makes more sense to "inline" it in the documentation and also clean it up a bit.

Added mention of Oracle DEV and inlined Postgres howto

---

mkdocs.yml

Disable line number in code highlight for better accessibility.
Empty link
A link contains no text.
If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users.
Remove the empty link or provide text within the link that describes the functionality and/or target of that link.
An anchor element has an href attribute, but contains no text (or only spaces) and no images with alternative text.
* [2.4.4 Link Purpose (In Context) (Level A)](https://webaim.org/standards/wcag/checklist#sc2.4.4)

Disable line numbers for better accessibility

---

docs/security/auth/azure-ad/configuration.md

fordi jeg brukte lang tid på å finne ut av dette selv. Forsto ikke hva som som var galt (i dev) med den object ID jeg hadde hentet ut fra AAD (i prod).
Burde kanskje dokumentasjonen si noe om hvor man går for å finne object ID for henholdsvis dev og prod? Jeg ble tipset om å gå hit https://developer.microsoft.com/en-us/graph/graph-explorer og logge på med en testbruker jeg hadde opprettet i [IDA](https://ida.intern.nav.no/).

azure-ad: clarify group ID uniqueness in different tenants

---

docs/observability/alerts.md

Fikk denne når jeg forsøkte å deploy:
Team not explicitly specified; attempting auto-detection...
Error: fatal: no team specified, and unable to auto-detect from nais.yaml

Må også legge inn team navn

---

docs/basics/access.md

Legg inn hint om debugging for dei som får feilmelding frå "cluster-info" ved installasjon av kubectl. 
Feilmeldinga ein får frå "cluster-info" skildrar eigentleg veldig godt at ein manglar "gke-gcloud-auth-plugin", men både eg og andre på teamet feilsøka ei stund før vi innsåg at vi kanskje heller burde lese heile feilmeldinga enn å google strofar frå den. 
Tenker det er fint å ha med eit "om dette ikkje fungerer"-notat i rettleiinga for installasjon av kubectl også, for oss som les den meir nøye enn output frå konsoll. Det er dessutan tryggjande å få bekrefta at det er eit kjend problem når ting ikkje fungerer som venta.
[Opphavleg spørsmål/forklaring av problemet på slack ](https://nav-it.slack.com/archives/C5KUST8N6/p1681373043321849)

Add instructions for debugging/installing missing gcloud plugin

---

docs/nais-application/access-policy.md

Ser ikke ms-graph dokumentert her (selv om det står andre steder i doc'en https://docs.nais.io/security/auth/azure-ad/configuration/?h=graph.mic#google-cloud-platform-gcp)

legg til default host

---

docs/cli/install.md
docs/device/install-tenant.md
docs/device/install.md

Moved the key to `/etc/apt/keyrings`, because of this line in `man sources.list`:
> The recommended locations for keyrings are /usr/share/keyrings for keyrings managed by packages, and /etc/apt/keyrings for keyrings managed by the system operator.

Update install instructions to use GAR for nais-ppa

---

docs/device/install.md

Nå som konsulentmaskiner skal ut av `"Pilot"` så har det vært klager på denne. Nå matcher den de faktiske D&Dene på eierskap.

updated device ownership

---

docs/clusters/migrating-databases-to-gcp.md

```
❯ kubectl exec -it gcloud /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
```

Bruk -- ved kubectl exec

---

docs/deployment/README.md
docs/guides/oci-migration.md

Siden vi deler dette opp i to jobber så trenger begge jobbene permissions.

guide: feil i permissions

---

docs/reference/tags.md
mkdocs.yml

This will make all tags clickable, and they will open the tags overview with an anchor to the given tag.

Add tags overview page

---

.github/workflows/main.yml
build.sh
docs/how-to-guides/naisdevice/install.md
docs/how-to-guides/observability/logs/kubectl.md
docs/how-to-guides/observability/tracing/correlate-traces-logs.md
docs/how-to-guides/persistence/redis/README.md

🔪 broken link stragglers

---

tenants/nav/how-to-guides/observability/logs/enable-secure-logs.md

Secure logs indices are created automatically, but without a couple of manual steps from Kibana admins before their creation they are not included into the lifecycle management, and require much more manual work later on to fix that. Added an explicit request for new teams about to produce secure logs to inform Kibana admins about that in advance.

Adding a step about warning Kibana admins of new teams

---

tenants/nav/reference/environments.md

Slet litt med å finne info om dette i docen og det har vært der tidligere. ref https://nav-it.slack.com/archives/CCSET7820/p1685536563209559

Info om blokkerte suffiks for nav.no i prod-gcp

---

docs/persistence/postgres/how-to/certification-sync-issues.md

Documenting manual client certification deletion for Postgres, in case of errors like https://nav-it.slack.com/archives/C5KUST8N6/p1716883403108279?thread_ts=1716882709.704449&cid=C5KUST8N6

Documenting manual client certification deletion for Postgres

---

docs/operate/cli/reference/postgres.md
docs/persistence/postgres/README.md
docs/persistence/postgres/explanations/cloud-sql-instance.md
docs/persistence/postgres/how-to/migrate-to-new-instance.md
docs/persistence/postgres/reference/README.md

Co-authored-by: Trong Nguyen <trong.huu.nguyen@nav.no>

Add documentation for cloudsql migration

---

docs/operate/naisdevice/how-to/install.md
docs/operate/naisdevice/how-to/uninstall.md
docs/operate/naisdevice/how-to/update.md

- Specify use of `nais-device` tenant package for tenants other than `nav`
- Standardise tab-formatting
- Separate instructions for `Windows (Scoop)` and `Windows (Manual)`
- Heading in Update instructions uses imperative case
Resolves #682

Correct tenant-specific update and uninstall instructions

---

docs/observability/logging/how-to/enable-secure-logs.md

Litt ekstra info i loggen om Logback config når applikasjonen starter opp. Dette var veldig nyttig for meg da jeg prøvde å finne ut hvorfor logging requests som var ment for Securelogs havnet i ordninær applogg istedenfor: Jeg kunne se at det var logback.xml-fila fra en av appens dependecies som ble brukt istedenfor min egen app sin logback.xml.

Legg til logging av Logback initialisering i eksempelkonfig

---

docs/operate/cli/reference/postgres.md

appname sto sist, men skal være først av argumentene ref: 
USAGE:
nais postgres users add [command options] appname username password

Fikset rekkefølge i nais postgres users add kommando

---

docs/operate/cli/reference/aiven.md
docs/persistence/kafka/README.md
docs/persistence/kafka/explanations/offset.md
docs/persistence/kafka/how-to/access.md
docs/persistence/kafka/reference/environment-variables.md
docs/persistence/kafka/reference/monitoring.md

I started this PR because half the links to Aiven docs were broken.
The issue was that Aiven was redirecting to broken URLs.
In the time it took to create this PR, Aiven had fixed their redirects.
I guess this PR is just updating the links to Aiven docs to avoid unnecessary redirects now 🤷
Maybe their redirects break again in the future. With this PR, hopefully we won't notice.
---
Here is the original description of the PR/issue, from before I double checked all the links just before clicking `Create PR`:
> Fixes a few broken links to Aiven docs. Aiven is redirecting them without the `/docs/` prefix, resulting in `404` pages.
> 
> Updates other Aiven links, removing subdomains (`docs`, `help` and `developer`) and updating paths, that redirect to `aiven.io/docs/[...]`.

Update links to Aiven docs
